topologies:
  build: &build
    name: build
    cpu: 2
    memory: 3800
  master_2repl_1client: &master_2repl_1client
    name: master_2repl_1client
    cpu: 5
    memory: 9100

jobs:
  fedora-28/build:
    requires: []
    priority: 100
    job:
      class: Build
      args:
        git_repo: '{git_repo}'
        git_refspec: '{git_refspec}'
        template: &ci-master-f28
          name: freeipa/ci-master-f28
          version: 0.1.9
        timeout: 1800
        topology: *build

  fedora-28/test_backup_and_restore_TestBackupAndRestoreWithReplica:
    requires: [fedora-28/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-28/build_url}'
        test_suite: test_integration/test_backup_and_restore.py::TestBackupAndRestoreWithReplica
        template: *ci-master-f28
        timeout: 7200
        topology: *master_2repl_1client
