topologies:
  build: &build
    name: build
    cpu: 2
    memory: 3800
  ad: &ad
    name: ad
    cpu: 6
    memory: 8000

jobs:
  fedora-29/build:
    requires: []
    priority: 100
    job:
      class: Build
      args:
        git_repo: '{git_repo}'
        git_refspec: '{git_refspec}'
        template: &ci-master-f29
          name: freeipa/ci-master-f29
          version: 0.2.0
        timeout: 1800
        topology: *build

  fedora-29/ad_tests:
    requires: [fedora-29/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-29/build_url}'
        test_suite: test_integration/test_idviews.py
        template: *ci-master-f29
        timeout: 20000
        topology: *ad
